[package]
name = "rbw"
version = "1.12.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"
include = ["src/**/*", "bin/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
aes = "0.8.4"
anyhow = "1.0.86"
argon2 = "0.5.3"
arrayvec = "0.7.4"
axum = "0.7.5"
base32 = "0.5.1"
base64 = "0.22.1"
block-padding = "0.3.3"
cbc = { version = "0.1.2", features = ["alloc", "std"] }
clap_complete = "4.5.11"
clap = { version = "4.5.11", features = ["wrap_help", "derive"] }
copypasta = "0.10.1"
daemonize = "0.5.0"
# TODO: directories 5.0.1 uses MPL code, which isn't license-compatible
# we should switch to something else at some point
directories = "=5.0.0"
env_logger = "0.11.5"
futures = "0.3.30"
futures-channel = "0.3.30"
futures-util = "0.3.30"
hkdf = "0.12.4"
hmac = { version = "0.12.1", features = ["std"] }
humantime = "2.1.0"
is-terminal = "0.4.12"
libc = "0.2.155"
log = "0.4.22"
open = "5.3.0"
pbkdf2 = "0.12.2"
percent-encoding = "2.3.1"
pkcs8 = "0.10.2"
rand = "0.8.5"
regex = "1.10.5"
region = "3.0.2"
reqwest = { version = "0.12.5", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rmpv = "1.3.0"
rsa = "0.9.6"
rustix = { version = "0.38.34", features = ["termios", "procfs", "process", "pipe"] }
serde_json = "1.0.120"
serde_path_to_error = "0.1.16"
serde_repr = "0.1.19"
serde = { version = "1.0.204", features = ["derive"] }
sha1 = "0.10.6"
sha2 = "0.10.8"
tempfile = "3.10.1"
terminal_size = "0.3.0"
textwrap = "0.16.1"
thiserror = "1.0.63"
tokio-stream = { version = "0.1.15", features = ["net"] }
tokio-tungstenite = { version = "0.23", features = ["rustls-tls-native-roots", "url"] }
tokio = { version = "1.39.2", features = ["full"] }
totp-lite = "2.0.1"
url = "2.5.2"
urlencoding = "2.1.3"
uuid = { version = "1.10.0", features = ["v4"] }
webauthn-authenticator-rs = { version="0.5.0", features = ["usb"], optional = true }
webauthn-rs-proto = { version="0.5.0", optional = true }
webauthn-rs = { version="0.5.0", optional = true }
zeroize = "1.8.1"

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]
assets = [
    ["target/release/rbw", "usr/bin/", "755"],
    ["target/release/rbw-agent", "usr/bin/", "755"],
    ["target/release/completion/bash", "usr/share/bash-completion/completions/rbw", "644"],
    ["target/release/completion/zsh", "usr/share/zsh/vendor-completions/_rbw", "644"],
    ["target/release/completion/fish", "usr/share/fish/completions/rbw.fish", "644"],
    ["README.md", "usr/share/doc/rbw/README", "644"],
]

[features]
# Enables webauthn 2-FA authenticaton, but requires openssl
webauthn = ["dep:webauthn-rs", "dep:webauthn-rs-proto", "dep:webauthn-authenticator-rs"]